version: '3'
services:
  impex:
    image: srste/srste:1.0.0.full
    command: npm run debug
    #command: npm run single
    environment:
      - NODE_ENV=production
      - NODE_ID=srste1
      - DB_USER=proxyuser
      - DB_PORT=3306
      - DB_HOST=192.168.0.109
      - DB_PASSWORD=srstee
      - DB_DATABASE=srstee
      - REDIS=192.168.0.109:6379
      - USE_REDIS=true
      - WORKFLOW_URL=http://192.168.0.109:8091
    #command: npm run start
    #command: node -e 'setTimeout(()=>console.log("Test!"), 10000000)'
    ports:
     - "8011:8080"
     - "2222:2222"
     - "9229:9229"
    restart: always
volumes:
    db_data: