version: '3.0'
services:
  rasa:
    image: rasa/rasa
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command:
      - run 
      - --enable-api
  action-server:
    image: rasa/rasa-sdk
    volumes:
      - ./actions:/app/actions
    ports:
      - 5055:5055
    environment:
      CHATBOT_SERVER_URL: "http://172.105.36.239"